### ISSUE TITLE
Set up a static page 

### ISSUE THREAD

**Issue by swhi3635** [learntouselinux/learntouselinux#1]
Let's get the ball rolling on this.  I'm not sure how the site is currently set up, but it seems like we should give ourselves a new starting point.

I assume we all want to build a robust infrastructure for this site (or whatever it will turn into), but we should at least have something simple to work with as we get started.

For now, I think a single instance running apache, nginx, etc. will be sufficient.  It shouldn't take long for us to write and deploy those configs.

**Comment by jerrywardlow** [comment]
Agreed, currently the static site is hosted on one of my throwaway boxes but it needs to be moved onto something permanent/dedicated that everyone can have access to.

**Comment by toozej** [comment]
I have working Hugo (static site generator) and Nginx Docker-compose configs ready to rock and roll from my personal site that we could easily repurpose. Happy to bring those to the "table" next meeting and show how they work, then we can decide if we wanna go that route or some other. 

https://github.com/toozej/static-site-template has the simplified, stripped out example. Could be stripped out more to remove Traefik bits.

**Comment by jerrywardlow** [comment]
Closing, creating a new issue in learntouselinux/app when we decided on a hosting provider.
