### ISSUE TITLE
Create Terraform config for DigitalOcean domain "learntouselinux.com"

### ISSUE THREAD

**Issue by jerrywardlow** [learntouselinux/learntouselinux#11]
Create and deploy Terraform configuration for the following DNS related elements:

**DigitalOcean Provider**
https://www.terraform.io/docs/providers/do/index.html
This should be self explanatory and is merely kickstarting the Terraform config file.

**DigitalOcean Domain**
https://www.terraform.io/docs/providers/do/r/domain.html
This configuration should only manage the creation of the domain resource, it should not create any records or manage any IP addresses.

https://github.com/learntouselinux/dns

**Comment by Bri997** [comment]
PR is merged at https://github.com/learntouselinux/dns/pull/1
