### ISSUE TITLE
Create Terraform config for DigitalOcean DNS A record "learntouselinux.com"

### ISSUE THREAD

**Issue by jerrywardlow** [learntouselinux/learntouselinux#12]
Create and deploy Terraform configuration for the following DNS related elements:

**DigitalOcean Record**
https://www.terraform.io/docs/providers/do/r/record.html
Configure DNS 'A' record for root domain of `learntouselinux.com`. This record should be configured to point to the *current host* for `learnouselinux.com`.

**Comment by jerrywardlow** [comment]
Off hold, #11 closed

**Comment by Bri997** [comment]
Closed and merged
