### ISSUE TITLE
Research GitHub Actions

### ISSUE THREAD

**Issue by jerrywardlow** [learntouselinux/learntouselinux#14]
We should have an open ended conversation about CI/CD platforms (GitHub Actions, TravisCI, CircleCI). I would like to implement a workflow in [learntouselinux/dns](https://github.com/learntouselinux/dns) that involves an automated `terraform plan` when pushing a branch, and `terraform apply` when new code is merged to master. This will eliminate needing developers to manage DigitalOcean API tokens, instead a common token can be managed in the CI/CD suite. Along with remote state being stored in a DigitalOcean Space, this will make updating DNS records painless, and hopefully be the groundwork for a flow that can be reused in [learntouselinux/infra](https://github.com/learntouselinux/infra).

**Comment by qpfiffer** [comment]
* TravisCI
* Jenkins (lol)
* CircleCI
* Github Actions
* [Drone](https://drone.io/)

**Comment by jerrywardlow** [comment]
Per the 10-15 meeting we have voted and decided to implement GitHub Actions. I'll take point on getting us setup and create some issues to further investigate.

**Comment by jerrywardlow** [comment]
Hashicorp recently updated their examples and action containers now that GitHub Actions has exited beta. I have a working prototype that can interact with a remote state maintained in DigitalOcean Spaces with all credentials stored in GitHub Actions. It works great! After some fine tuning I hope to have a prototype available for our use case.
