### ISSUE TITLE
How to setup new DNS records 

### ISSUE THREAD

**Issue by yevgenybulochnik** [learntouselinux/learntouselinux#19]
Figure out how to create the DNS records for the new DO box. We will need to remove the old ip address in the DNS repo and assign the new one corresponding to the new DO box.

**Comment by yevgenybulochnik** [comment]
Per 10/15  meeting. Once a new DO box is created, a PR will need to be opened in the DNS repo to update the server IP .

**Comment by jerrywardlow** [comment]
Does anything else need to be done here or does the above comment wrap things up?
