### ISSUE TITLE
Create an organization account with DigitalOcean

### ISSUE THREAD

**Issue by swhi3635** [learntouselinux/learntouselinux#2]
Let's set up an org account with AWS or some other provider with a free tier. From there, we can create individual accounts for whomever on the team wants one.

**Comment by jerrywardlow** [comment]
Taking this over as I'll be handling billing.

**Comment by jerrywardlow** [comment]
Per the 10/08 meeting we've decided on DigitalOcean as a primary provider. I'll create an organization account and begin adding users.

**Comment by jerrywardlow** [comment]
Users have been invited!

**Comment by jerrywardlow** [comment]
Done, all users have accounts.
