### ISSUE TITLE
Determine best method for accessing Droplets during initial provisioning

### ISSUE THREAD

**Issue by swhi3635** [learntouselinux/learntouselinux#20]
When creating a new droplet, DigitalOcean provides two initial access methods:
 - Select the SSH key(s) that have already been added to the DigitalOcean project account
 - Have DO email you a username and password

We plan to rely on `cloud-init` to install everyone's SSH keys, so we can avoid using either of the two above options.  Ideally, we don't have to specify any SSH keys to DO directly, nor do we  receive any emails containing login credentials.

So far, we know that omitting any SSH keys in Terraform and applying the config triggers the credential email.  We need to test various scenarios to see whether or not we can actually accomplish this.

**Comment by yevgenybulochnik** [comment]
Can confirm that user-data does not solve the issue.  You still end up getting the credential email, even when importing ssh keys with user-data.

**Comment by yevgenybulochnik** [comment]
Jerry kindly offered up a public key. We removed all current keys in the DO account, but left one keeb key.  This seems to have done the trick. When running terraform apply using that public keys fingerprint no email is sent.
