### ISSUE TITLE
Remove ssh root access

### ISSUE THREAD

**Issue by yevgenybulochnik** [learntouselinux/learntouselinux#22]
Since a public ssh key was required to prevent the DO credential email, root ssh access is now available using this ssh key. We need to remove this and really figure out how to remove it automatically on server creation.

**Comment by jerrywardlow** [comment]
Edited `/etc/ssh/sshd_config` to update line
```
PermitRootLogin yes
```
to
```
PermitRootLogin no
```
Ran `sudo systemctl restart sshd` to force daemon to use new config.

Confirmed that root login is no longer possible:
```
$ ssh root@138.68.44.28
root@138.68.44.28: Permission denied (publickey).
```
