### ISSUE TITLE
Setup apache

### ISSUE THREAD

**Issue by yevgenybulochnik** [learntouselinux/learntouselinux#23]
Apache needs to be setup, including a virtual host file to serve our flat html file. Also we need to setup the flat html file to be served.

**Comment by sanchezricky** [comment]
I have completed the tasks provided on the Readme for version1. I installed apache2, including a virtual host file to serve the flat html file.

**Comment by jerrywardlow** [comment]
Is this done?

**Comment by sanchezricky** [comment]
Yes. I am closing this ticket
