### ISSUE TITLE
Alphabetize user-data ssh key list 

### ISSUE THREAD

**Issue by yevgenybulochnik** [learntouselinux/learntouselinux#25]
We should alphabetize the ssh key list in the user-data on the infra repo, however this should be done only after we figure out automating the setup of apache, fail2ban and removing the root ssh key

**Comment by swhi3635** [comment]
I think this should be labeled something other than v1, since it is blocked on v2 issues.  I'd be fine with labeling this v2, or creating a new label and/or column for blocked issues.
