### ISSUE TITLE
Create issue template

### ISSUE THREAD

**Issue by toozej** [learntouselinux/learntouselinux#29]
- problem statement: what needs to be done and why
- criteria for success
- ways one might do the task, including alternatives, documentation and links

**Comment by toozej** [comment]
Will be completed in:
https://github.com/learntouselinux/app/pull/4
https://github.com/learntouselinux/dns/pull/4
https://github.com/learntouselinux/infra/pull/4
https://github.com/learntouselinux/learntouselinux/pull/34

**Comment by jerrywardlow** [comment]
Can we remove the `@TAG_REVIEWER` part from these? The reviewer already gets a notification when they're assigned as a reviewer, there's no reason to tag them in the comments as well.

**Comment by toozej** [comment]
That's good feedback @jerrywardlow , I've taken it into account and either updated the existing PRs, or created and merged new ones for the PRs which have already been merged
