### ISSUE TITLE
Create repositories for Ansible, Terraform, and application code

### ISSUE THREAD

**Issue by swhi3635** [learntouselinux/learntouselinux#5]
Do the thing

**Comment by yevgenybulochnik** [comment]
Everyone good with ltul-ansible, ltul-terraform, ltul-app. I  was thinking the current repo, for the org will just be a giant readme that links to the other repos. Could also use ltl prefix instead of ltul.

**Comment by jerrywardlow** [comment]
Two things: are we using Ansible and Terraform, and are we having separate repositories for configuration management, infrastructure management, and application code?

**Comment by jerrywardlow** [comment]
With regards to naming it doesn't make sense to tag the repositories with `ltul` considering they live within the org `learntouselinux` and would already be namespaced. Example: `learntouselinux/ansible`, `learntouselinux/terraform`.

**Comment by yevgenybulochnik** [comment]
Closing this issue for now as this was discussed at the last meeting. App repo has been created already.
